title: "Subhash Kotaru"
description: "Developer"
url: "https://subhashkotaru.github.io"
baseurl: "/mywebsite"

author:
  name: "Subhash Kotaru"
  email: "sk12154@nyu.edu"
  phone: "3322801757"
  github: "subhashkotaru"
  linkedin: "subhash-kotaru"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blogs/:slug/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "pages"
    values:
      layout: "page"
